### ISSUE TITLE
code review for the Todo-react app

### ISSUE THREAD

**Issue by Kaweesi-Matia** [myaserkhan/Todo-App-With-REACT#2]
## Changes Required ♻️ 
**Hi @myaserkhan** ,
Good job so far!
There are some issues that you still need to work on  but you are almost there! 👍 

## To Highlight 🎉

- No linter errors. ✔️

- Gitflow is followed. ✔️

- Professional README file. ✔️
- The project is working well and is amazing. ✔️ 

<img src="https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966">

## REQUIRED CHANGES ♻️ 

**There are some issues I would like to point out in your work:**

- Your PR has a good title but you didn't  include a descriptive summary for it. kindly fix this issue

- It is important for you to deploy your project and add a link to the live demo on your [readme file]

## Suggested Fix

- In order to deploy your project you can simply run the code `npm install gh-pages` or you can deploy using netlify or vercel.
_kindly let me know if you have been able to deploy your project or if you require additional help._
_Cheers and happy coding_ 👏 👏 👏,
_Kaweesi Matia_

**Comment by myaserkhan** [comment]
Live demo is optional and React application don't work properly when you deploy them on GitHub pages.
